apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  type: NodePort
  selector:
    pod: devops-app
  ports:
    - name: devops-app-port
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
  labels:
    component: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: devops-app
  template:
    metadata:
      labels:
        pod: devops-app
    spec:
      containers:
        - name: devops-app
          image: dienvm1/devops-capstone
          imagePullPolicy: Always
          ports:
            - containerPort: 80
